version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: 'my-pos-post'
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

networks:
  my-pos-post:
    driver: bridge